# Generated by Django 3.0.2 on 2020-01-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backcountry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryyearindicator',
            name='value',
            field=models.DecimalField(decimal_places=5, max_digits=19),
        ),
    ]
